export const FLORIDA_CITIES = [
  'Jacksonville',
  'Miami',
  'Tampa',
  'Orlando',
  'St. Petersburg',
  'Hialeah',
  'Tallahassee',
  'Fort Lauderdale',
  'Port St. Lucie',
  'Cape Coral',
  'Pembroke Pines',
  'Hollywood',
  'Gainesville',
  'Miramar',
  'Coral Springs',
  'Lakeland',
  'Palm Bay',
  'Pompano Beach',
  'West Palm Beach',
  'Clearwater',
  'Boca Raton',
  'Bradenton',
  'Daytona Beach',
  'Deltona',
  'Melbourne',
  'Deerfield Beach',
  'Palm Coast',
  'Fort Myers',
  'Sanford',
  'Sunrise',
  'Pensacola',
  'Kissimmee',
  'Ocala',
  'Sarasota',
  'Naples',
  'Homestead',
  'Largo',
  'North Port',
  'Coconut Creek',
  'Boynton Beach',
  'Lauderhill',
  'Wichita Falls',
  'Miami Gardens',
  'Miami Beach',
  'Key West',
  'Gainesville',
  'Tallahassee',
];
