-- Weekly-cached AI feedback summary for the Dashboard's Feedback card.
-- Regenerated by the generate-weekly-feedback-summaries Edge Function
-- (invoked by cron, see 061_weekly_feedback_summary_cron.sql) — only for
-- users whose badge/note counts changed since the last generation, same
-- cost-saving pattern as Amazon's cached AI review summaries. Never written
-- to directly by the client; the client only ever reads its own row.
CREATE TABLE public.community_summary_cache (
  user_id           UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  summary           TEXT NOT NULL,
  badge_count_at_gen INTEGER NOT NULL,
  note_count_at_gen  INTEGER NOT NULL,
  generated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.community_summary_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own cached summary"
  ON public.community_summary_cache FOR SELECT
  USING (auth.uid() = user_id);

-- Same "not enough data yet" floor as the client's old
-- hooks/useCommunitySummary.ts MIN_FEEDBACK_FOR_SUMMARY.
-- Returns one row per user whose current badge+note counts differ from
-- what's cached (or who has no cache row yet) and who clears that floor —
-- i.e. exactly the users the weekly cron job needs to (re)generate for.
-- SECURITY DEFINER because this scans every user's badges/notes, which RLS
-- on those tables otherwise restricts to each user's own rows.
CREATE OR REPLACE FUNCTION public.get_users_needing_summary_refresh()
RETURNS TABLE (user_id UUID, badge_count BIGINT, note_count BIGINT)
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  WITH badge_totals AS (
    SELECT receiver_id, COUNT(*) AS badge_count
    FROM public.ride_badges
    GROUP BY receiver_id
  ),
  note_totals AS (
    SELECT receiver_id, COUNT(*) AS note_count
    FROM public.feedback_notes
    GROUP BY receiver_id
  ),
  current_totals AS (
    SELECT
      COALESCE(b.receiver_id, n.receiver_id) AS user_id,
      COALESCE(b.badge_count, 0) AS badge_count,
      COALESCE(n.note_count, 0) AS note_count
    FROM badge_totals b
    FULL OUTER JOIN note_totals n ON n.receiver_id = b.receiver_id
  )
  SELECT ct.user_id, ct.badge_count, ct.note_count
  FROM current_totals ct
  LEFT JOIN public.community_summary_cache c ON c.user_id = ct.user_id
  WHERE (ct.badge_count + ct.note_count) >= 5
    AND (
      c.user_id IS NULL
      OR c.badge_count_at_gen IS DISTINCT FROM ct.badge_count
      OR c.note_count_at_gen IS DISTINCT FROM ct.note_count
    );
$$;

GRANT EXECUTE ON FUNCTION public.get_users_needing_summary_refresh() TO service_role;
